apiVersion: v2
name: k8s-gather
description: Diagnostic data collection tool for AI/ML workloads on various Kubernetes distro
type: application
version: 1.2.0-rc1
appVersion: "1.2.0-rc1"
keywords:
  - kubernetes
  - kserve
  - llm-d
  - ai-ml
  - openshift
  - ODH
  - RHOAI
  - cks 
  - aks
home: https://github.com/zdtsw/k8s-gather
sources:
  - https://github.com/zdtsw/k8s-gather
maintainers:
  - name: Wen Zhou
    email: wenzhou@redhat.com
